[package]
name = "hello-world-sqlite-rs"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
sayiir-runtime = { path = "../sayiir-runtime", features = ["macros", "rkyv"] }
sayiir-persistence = { path = "../sayiir-persistence" }
sayiir-diesel = { path = "../sayiir-diesel", features = ["sqlite"] }
sayiir-core = { path = "../sayiir-core" }
tokio = { version = "1", features = ["rt", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
